name: Playwright Action Scrapper

on:
  schedule:
    - cron: "0 */12 * * *"   # roda a cada 6 horas (opcional)
  workflow_dispatch:        # permite rodar manualmente

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
        MONGO_COLLECTION_1: ${{ secrets.MONGO_COLLECTION_1 }}
        MONGO_COLLECTION_2: ${{ secrets.MONGO_COLLECTION_2 }}
        MONGO_COLLECTION_3: ${{ secrets.MONGO_COLLECTION_3 }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.10"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Instalar browsers do Playwright
        run: |
          playwright install --with-deps

      - name: Rodar scrapper
        run: |
          python src/main.py